// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_repository

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RepositoryResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Markdown description",
				MarkdownDescription: "Markdown description",
				Default:             stringdefault.StaticString(""),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Repository name",
				MarkdownDescription: "Repository name",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace": schema.StringAttribute{
				Required:            true,
				Description:         "Repository namespace. Should be an organization name or username",
				MarkdownDescription: "Repository namespace. Should be an organization name or username",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"visibility": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Repository visibility. Should be private or public. Defaults to private.",
				MarkdownDescription: "Repository visibility. Should be private or public. Defaults to private.",
				Validators: []validator.String{
					stringvalidator.OneOf([]string{"private", "public"}...),
				},
				Default: stringdefault.StaticString("private"),
			},
		},
	}
}

type RepositoryModel struct {
	Description types.String `tfsdk:"description"`
	Name        types.String `tfsdk:"name"`
	Namespace   types.String `tfsdk:"namespace"`
	Visibility  types.String `tfsdk:"visibility"`
}
