/*
Quay Frontend

This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.

API version: v1
Contact: admin@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quay_api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NewPrototypeActivatingUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewPrototypeActivatingUser{}

// NewPrototypeActivatingUser Repository creating user to whom the rule should apply
type NewPrototypeActivatingUser struct {
	// The username for the activating_user
	Name string `json:"name"`
}

type _NewPrototypeActivatingUser NewPrototypeActivatingUser

// NewNewPrototypeActivatingUser instantiates a new NewPrototypeActivatingUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewPrototypeActivatingUser(name string) *NewPrototypeActivatingUser {
	this := NewPrototypeActivatingUser{}
	this.Name = name
	return &this
}

// NewNewPrototypeActivatingUserWithDefaults instantiates a new NewPrototypeActivatingUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewPrototypeActivatingUserWithDefaults() *NewPrototypeActivatingUser {
	this := NewPrototypeActivatingUser{}
	return &this
}

// GetName returns the Name field value
func (o *NewPrototypeActivatingUser) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NewPrototypeActivatingUser) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NewPrototypeActivatingUser) SetName(v string) {
	o.Name = v
}

func (o NewPrototypeActivatingUser) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewPrototypeActivatingUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *NewPrototypeActivatingUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewPrototypeActivatingUser := _NewPrototypeActivatingUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewPrototypeActivatingUser)

	if err != nil {
		return err
	}

	*o = NewPrototypeActivatingUser(varNewPrototypeActivatingUser)

	return err
}

type NullableNewPrototypeActivatingUser struct {
	value *NewPrototypeActivatingUser
	isSet bool
}

func (v NullableNewPrototypeActivatingUser) Get() *NewPrototypeActivatingUser {
	return v.value
}

func (v *NullableNewPrototypeActivatingUser) Set(val *NewPrototypeActivatingUser) {
	v.value = val
	v.isSet = true
}

func (v NullableNewPrototypeActivatingUser) IsSet() bool {
	return v.isSet
}

func (v *NullableNewPrototypeActivatingUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewPrototypeActivatingUser(val *NewPrototypeActivatingUser) *NullableNewPrototypeActivatingUser {
	return &NullableNewPrototypeActivatingUser{value: val, isSet: true}
}

func (v NullableNewPrototypeActivatingUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewPrototypeActivatingUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
