/*
Quay Frontend

This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.

API version: v1
Contact: admin@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quay_api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AddLabel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddLabel{}

// AddLabel Adds a label to a manifest
type AddLabel struct {
	// The key for the label
	Key string `json:"key"`
	// The value for the label
	Value string `json:"value"`
}

type _AddLabel AddLabel

// NewAddLabel instantiates a new AddLabel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddLabel(key string, value string) *AddLabel {
	this := AddLabel{}
	this.Key = key
	this.Value = value
	return &this
}

// NewAddLabelWithDefaults instantiates a new AddLabel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddLabelWithDefaults() *AddLabel {
	this := AddLabel{}
	return &this
}

// GetKey returns the Key field value
func (o *AddLabel) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *AddLabel) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *AddLabel) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *AddLabel) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *AddLabel) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *AddLabel) SetValue(v string) {
	o.Value = v
}

func (o AddLabel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddLabel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *AddLabel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddLabel := _AddLabel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddLabel)

	if err != nil {
		return err
	}

	*o = AddLabel(varAddLabel)

	return err
}

type NullableAddLabel struct {
	value *AddLabel
	isSet bool
}

func (v NullableAddLabel) Get() *AddLabel {
	return v.value
}

func (v *NullableAddLabel) Set(val *AddLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableAddLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableAddLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddLabel(val *AddLabel) *NullableAddLabel {
	return &NullableAddLabel{value: val, isSet: true}
}

func (v NullableAddLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
