/*
Quay Frontend

This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.

API version: v1
Contact: admin@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quay_api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NewStarredRepository type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewStarredRepository{}

// NewStarredRepository struct for NewStarredRepository
type NewStarredRepository struct {
	// Namespace in which the repository belongs
	Namespace string `json:"namespace"`
	// Repository name
	Repository string `json:"repository"`
}

type _NewStarredRepository NewStarredRepository

// NewNewStarredRepository instantiates a new NewStarredRepository object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewStarredRepository(namespace string, repository string) *NewStarredRepository {
	this := NewStarredRepository{}
	this.Namespace = namespace
	this.Repository = repository
	return &this
}

// NewNewStarredRepositoryWithDefaults instantiates a new NewStarredRepository object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewStarredRepositoryWithDefaults() *NewStarredRepository {
	this := NewStarredRepository{}
	return &this
}

// GetNamespace returns the Namespace field value
func (o *NewStarredRepository) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *NewStarredRepository) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *NewStarredRepository) SetNamespace(v string) {
	o.Namespace = v
}

// GetRepository returns the Repository field value
func (o *NewStarredRepository) GetRepository() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value
// and a boolean to check if the value has been set.
func (o *NewStarredRepository) GetRepositoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Repository, true
}

// SetRepository sets field value
func (o *NewStarredRepository) SetRepository(v string) {
	o.Repository = v
}

func (o NewStarredRepository) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewStarredRepository) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["namespace"] = o.Namespace
	toSerialize["repository"] = o.Repository
	return toSerialize, nil
}

func (o *NewStarredRepository) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"namespace",
		"repository",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewStarredRepository := _NewStarredRepository{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewStarredRepository)

	if err != nil {
		return err
	}

	*o = NewStarredRepository(varNewStarredRepository)

	return err
}

type NullableNewStarredRepository struct {
	value *NewStarredRepository
	isSet bool
}

func (v NullableNewStarredRepository) Get() *NewStarredRepository {
	return v.value
}

func (v *NullableNewStarredRepository) Set(val *NewStarredRepository) {
	v.value = val
	v.isSet = true
}

func (v NullableNewStarredRepository) IsSet() bool {
	return v.isSet
}

func (v *NullableNewStarredRepository) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewStarredRepository(val *NewStarredRepository) *NullableNewStarredRepository {
	return &NullableNewStarredRepository{value: val, isSet: true}
}

func (v NullableNewStarredRepository) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewStarredRepository) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
