/*
Quay Frontend

This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.

API version: v1
Contact: admin@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quay_api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RepoUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepoUpdate{}

// RepoUpdate Fields which can be updated in a repository.
type RepoUpdate struct {
	// Markdown encoded description for the repository
	Description string `json:"description"`
}

type _RepoUpdate RepoUpdate

// NewRepoUpdate instantiates a new RepoUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepoUpdate(description string) *RepoUpdate {
	this := RepoUpdate{}
	this.Description = description
	return &this
}

// NewRepoUpdateWithDefaults instantiates a new RepoUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepoUpdateWithDefaults() *RepoUpdate {
	this := RepoUpdate{}
	return &this
}

// GetDescription returns the Description field value
func (o *RepoUpdate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RepoUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RepoUpdate) SetDescription(v string) {
	o.Description = v
}

func (o RepoUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepoUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *RepoUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepoUpdate := _RepoUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRepoUpdate)

	if err != nil {
		return err
	}

	*o = RepoUpdate(varRepoUpdate)

	return err
}

type NullableRepoUpdate struct {
	value *RepoUpdate
	isSet bool
}

func (v NullableRepoUpdate) Get() *RepoUpdate {
	return v.value
}

func (v *NullableRepoUpdate) Set(val *RepoUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRepoUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRepoUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepoUpdate(val *RepoUpdate) *NullableRepoUpdate {
	return &NullableRepoUpdate{value: val, isSet: true}
}

func (v NullableRepoUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepoUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
