/*
Quay Frontend

This API allows you to perform many of the operations required to work with Quay repositories, users, and organizations.

API version: v1
Contact: admin@example.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package quay_api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TeamPermission type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TeamPermission{}

// TeamPermission Description of a team permission.
type TeamPermission struct {
	// Role to use for the team
	Role string `json:"role"`
}

type _TeamPermission TeamPermission

// NewTeamPermission instantiates a new TeamPermission object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTeamPermission(role string) *TeamPermission {
	this := TeamPermission{}
	this.Role = role
	return &this
}

// NewTeamPermissionWithDefaults instantiates a new TeamPermission object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTeamPermissionWithDefaults() *TeamPermission {
	this := TeamPermission{}
	return &this
}

// GetRole returns the Role field value
func (o *TeamPermission) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *TeamPermission) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *TeamPermission) SetRole(v string) {
	o.Role = v
}

func (o TeamPermission) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TeamPermission) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *TeamPermission) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTeamPermission := _TeamPermission{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTeamPermission)

	if err != nil {
		return err
	}

	*o = TeamPermission(varTeamPermission)

	return err
}

type NullableTeamPermission struct {
	value *TeamPermission
	isSet bool
}

func (v NullableTeamPermission) Get() *TeamPermission {
	return v.value
}

func (v *NullableTeamPermission) Set(val *TeamPermission) {
	v.value = val
	v.isSet = true
}

func (v NullableTeamPermission) IsSet() bool {
	return v.isSet
}

func (v *NullableTeamPermission) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTeamPermission(val *TeamPermission) *NullableTeamPermission {
	return &NullableTeamPermission{value: val, isSet: true}
}

func (v NullableTeamPermission) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTeamPermission) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
