/*
Quay Frontend

Testing OrganizationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package quay_api

import (
	"context"
	openapiclient "github.com/enthought/terraform-provider-quay/quay_api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_quay_api_OrganizationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OrganizationAPIService ChangeOrganizationDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.ChangeOrganizationDetails(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService CreateOrganization", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.OrganizationAPI.CreateOrganization(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService CreateOrganizationApplication", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.CreateOrganizationApplication(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService DeleteAdminedOrganization", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.DeleteAdminedOrganization(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService DeleteOrganizationApplication", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string
		var clientId string

		httpRes, err := apiClient.OrganizationAPI.DeleteOrganizationApplication(context.Background(), orgname, clientId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetApplicationInformation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var clientId string

		httpRes, err := apiClient.OrganizationAPI.GetApplicationInformation(context.Background(), clientId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetOrganization", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.GetOrganization(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetOrganizationApplication", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string
		var clientId string

		httpRes, err := apiClient.OrganizationAPI.GetOrganizationApplication(context.Background(), orgname, clientId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetOrganizationApplications", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.GetOrganizationApplications(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetOrganizationCollaborators", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.GetOrganizationCollaborators(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetOrganizationMember", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string
		var membername string

		httpRes, err := apiClient.OrganizationAPI.GetOrganizationMember(context.Background(), orgname, membername).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService GetOrganizationMembers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string

		httpRes, err := apiClient.OrganizationAPI.GetOrganizationMembers(context.Background(), orgname).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService RemoveOrganizationMember", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string
		var membername string

		httpRes, err := apiClient.OrganizationAPI.RemoveOrganizationMember(context.Background(), orgname, membername).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OrganizationAPIService UpdateOrganizationApplication", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var orgname string
		var clientId string

		httpRes, err := apiClient.OrganizationAPI.UpdateOrganizationApplication(context.Background(), orgname, clientId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
