/*
Quay Frontend

Testing ErrorAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package quay_api

import (
	"context"
	openapiclient "github.com/enthought/terraform-provider-quay/quay_api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_quay_api_ErrorAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ErrorAPIService GetErrorDescription", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var errorType string

		resp, httpRes, err := apiClient.ErrorAPI.GetErrorDescription(context.Background(), errorType).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
