/*
Quay Frontend

Testing GlobalmessagesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package quay_api

import (
	"context"
	openapiclient "github.com/enthought/terraform-provider-quay/quay_api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_quay_api_GlobalmessagesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GlobalmessagesAPIService CreateGlobalMessage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.GlobalmessagesAPI.CreateGlobalMessage(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GlobalmessagesAPIService DeleteGlobalMessage", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var uuid string

		httpRes, err := apiClient.GlobalmessagesAPI.DeleteGlobalMessage(context.Background(), uuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GlobalmessagesAPIService GetGlobalMessages", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.GlobalmessagesAPI.GetGlobalMessages(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
