/*
Quay Frontend

Testing SuperuserAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package quay_api

import (
	"context"
	openapiclient "github.com/enthought/terraform-provider-quay/quay_api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_quay_api_SuperuserAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SuperuserAPIService ApproveServiceKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var kid string

		httpRes, err := apiClient.SuperuserAPI.ApproveServiceKey(context.Background(), kid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ChangeInstallUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var username string

		httpRes, err := apiClient.SuperuserAPI.ChangeInstallUser(context.Background(), username).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ChangeOrganization", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var name string

		httpRes, err := apiClient.SuperuserAPI.ChangeOrganization(context.Background(), name).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ChangeOrganizationQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var quotaId string
		var namespace string

		httpRes, err := apiClient.SuperuserAPI.ChangeOrganizationQuotaSuperUser(context.Background(), quotaId, namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ChangeUserQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var quotaId string
		var namespace string

		httpRes, err := apiClient.SuperuserAPI.ChangeUserQuotaSuperUser(context.Background(), quotaId, namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService CreateInstallUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SuperuserAPI.CreateInstallUser(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService CreateOrganizationQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		httpRes, err := apiClient.SuperuserAPI.CreateOrganizationQuotaSuperUser(context.Background(), namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService CreateServiceKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SuperuserAPI.CreateServiceKey(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService CreateUserQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		httpRes, err := apiClient.SuperuserAPI.CreateUserQuotaSuperUser(context.Background(), namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService DeleteInstallUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var username string

		httpRes, err := apiClient.SuperuserAPI.DeleteInstallUser(context.Background(), username).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService DeleteOrganization", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var name string

		httpRes, err := apiClient.SuperuserAPI.DeleteOrganization(context.Background(), name).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService DeleteOrganizationQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var quotaId string
		var namespace string

		httpRes, err := apiClient.SuperuserAPI.DeleteOrganizationQuotaSuperUser(context.Background(), quotaId, namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService DeleteServiceKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var kid string

		httpRes, err := apiClient.SuperuserAPI.DeleteServiceKey(context.Background(), kid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService DeleteUserQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var quotaId string
		var namespace string

		httpRes, err := apiClient.SuperuserAPI.DeleteUserQuotaSuperUser(context.Background(), quotaId, namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService GetInstallUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var username string

		httpRes, err := apiClient.SuperuserAPI.GetInstallUser(context.Background(), username).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService GetRepoBuildLogsSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var buildUuid string

		httpRes, err := apiClient.SuperuserAPI.GetRepoBuildLogsSuperUser(context.Background(), buildUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService GetRepoBuildStatusSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repository string
		var buildUuid string

		httpRes, err := apiClient.SuperuserAPI.GetRepoBuildStatusSuperUser(context.Background(), repository, buildUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService GetRepoBuildSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repository string
		var buildUuid string

		httpRes, err := apiClient.SuperuserAPI.GetRepoBuildSuperUser(context.Background(), repository, buildUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService GetServiceKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var kid string

		httpRes, err := apiClient.SuperuserAPI.GetServiceKey(context.Background(), kid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ListAllLogs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SuperuserAPI.ListAllLogs(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ListAllUsers", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SuperuserAPI.ListAllUsers(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ListOrganizationQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		httpRes, err := apiClient.SuperuserAPI.ListOrganizationQuotaSuperUser(context.Background(), namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ListServiceKeys", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.SuperuserAPI.ListServiceKeys(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService ListUserQuotaSuperUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var namespace string

		httpRes, err := apiClient.SuperuserAPI.ListUserQuotaSuperUser(context.Background(), namespace).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SuperuserAPIService UpdateServiceKey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var kid string

		httpRes, err := apiClient.SuperuserAPI.UpdateServiceKey(context.Background(), kid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
